name: flutter_store_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  analyzer: ^6.2.0
  dartz: ^0.10.1
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1
  shared_preferences: ^2.2.1

dev_dependencies:
  build_runner: ^2.1.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
  freezed: ^2.4.2

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets\fonts\Montserrat-Regular.ttf
          weight: 400
        - asset: assets\fonts\Montserrat-Light.ttf
          weight: 300
        - asset: assets\fonts\Montserrat-Medium.ttf
          weight: 500
        - asset: assets\fonts\Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\Montserrat-Bold.ttf
          weight: 700

  assets:
    - assets/images/splash_logo.png
    - assets/images/onboarding_logo1.svg
    - assets/images/onboarding_logo2.svg
    - assets/images/onboarding_logo3.svg
    - assets/images/onboarding_logo4.svg
