name: flutter_store_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  analyzer: ^6.2.0
  carousel_slider: ^4.2.1
  country_code_picker: ^3.0.0
  dartz: ^0.10.1
  dio: ^5.3.2
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  image_picker: ^1.0.4
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.8.1
  lottie: ^2.6.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.1
  easy_localization: ^3.0.3

dev_dependencies:
  build_runner: ^2.1.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets\fonts\Montserrat-Regular.ttf
          weight: 400
        - asset: assets\fonts\Montserrat-Light.ttf
          weight: 300
        - asset: assets\fonts\Montserrat-Medium.ttf
          weight: 500
        - asset: assets\fonts\Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\Montserrat-Bold.ttf
          weight: 700

  assets:
    - assets/images/splash_logo.png
    - assets/images/onboarding_logo1.svg
    - assets/images/onboarding_logo2.svg
    - assets/images/onboarding_logo3.svg
    - assets/images/onboarding_logo4.svg
    - assets/images/change_lang_ic.svg
    - assets/images/invite_friends_ic.svg
    - assets/images/logout_ic.svg
    - assets/images/contact_us_ic.svg
    - assets/images/settings_right_arrow_ic.svg
    - assets/json/empty.json
    - assets/json/error.json
    - assets/json/loading.json
    - assets/json/success.json
    - assets/l10n/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/splash_logo.png"
  adaptive_icon_background: "#ED9728"
  remove_alpha_ios: true
  background_color_ios: "#ED9728"
